"""
Render smoke test — CI safety net, not a design tool.

Every real batch is generated by Mistral + runner.py, but a broken
carousel_engine.py (a typo in a GitHub web edit, a stray unmatched paren,
a param rename that breaks a call site) wouldn't be caught until the
7:37am cron actually runs and either crashes or silently emails Ryan
broken images. This script renders one synthetic carousel per format
(checklist, steal-this, myth-buster, comparison, before-after) using
fake copy, covering every render path including the optional
before/after and compare_a/compare_b strips. If anything raises, this
script exits non-zero and the render_smoke_test.yml workflow fails loud
on the commit that broke it — Ryan gets a red X on GitHub instead of a
silent failure days later.

Not a substitute for reading the images — just a "did it crash" check.
"""

import os
import sys
import shutil
import carousel_engine as ce

FORMATS = ["checklist", "steal-this", "myth-buster", "comparison", "before-after"]
OUT_DIR = "/tmp/smoke_test_render"


def make_sample(fmt):
    body = [
        {"text": f"Sample body slide {i} for the {fmt} smoke test, long enough to wrap.", "keyword": f"slide {i}"}
        for i in range(1, 7)
    ]
    if fmt == "before-after":
        body[0]["before"] = "€45/lead"
        body[0]["after"] = "€15/lead"
    if fmt == "comparison":
        body[0]["compare_a"] = "Manual bidding"
        body[0]["compare_b"] = "Automated bidding"
    return {
        "niche": "Google Ads",
        "angle": "curiosity",
        "format": fmt,
        "hook_slide": f"Smoke test hook for {fmt} format",
        "hook_pop_phrase": "Smoke test",
        "bridge_slide": f"Smoke test bridge for {fmt}",
        "bridge_pop_phrase": "Smoke test",
        "body_slides": body,
        "recap_slide": [f"Recap point {i} of some reasonable length" for i in range(1, 7)],
        "cta_slide": "Smoke test cta context line",
        "cta_word": "GUIDE",
        "cta_promise": "the exact template",
        "cta_save_line": f"Save this for your next {fmt} review",
        "cta_support": "Free this week",
        "caption": "Smoke test caption. #test #marketing",
    }


def main():
    if os.path.exists(OUT_DIR):
        shutil.rmtree(OUT_DIR)
    os.makedirs(OUT_DIR, exist_ok=True)

    failures = []
    for fmt in FORMATS:
        try:
            sample = make_sample(fmt)
            paths = ce.render_carousel(sample, "2026-01-01", os.path.join(OUT_DIR, fmt))
            if not paths or len(paths) != 10:
                failures.append(f"{fmt}: expected 10 slide images, got {len(paths) if paths else 0}")
            else:
                print(f"OK  {fmt}: {len(paths)} slides rendered")
        except Exception as e:
            failures.append(f"{fmt}: {type(e).__name__}: {e}")

    shutil.rmtree(OUT_DIR, ignore_errors=True)

    if failures:
        print("\nSMOKE TEST FAILED:")
        for f in failures:
            print(f"  - {f}")
        sys.exit(1)

    print("\nAll formats rendered cleanly. Smoke test passed.")


if __name__ == "__main__":
    main()
